[build]
  command = "rm -rf dist && npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Serve static files directly
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200
  force = true

# Serve images with proper cache headers
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

# Force fresh social share image
[[headers]]
  for = "/images/ct-business-automation-results.webp"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Handle 404s properly for Astro static site
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"